language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/build-all.sh
notifications:
  email:
    on_success: never
    on_failure: always
