version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: find-a-tutor.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
  front:
    image: front
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: find-a-tutor.front
    environment: 
      - UrlBasePath=http://api:80
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8000:80
    depends_on:
      - api