version: "3.5"
services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: find-a-tutor.db
    restart: unless-stopped
    environment:
      SA_PASSWORD: "Abc12345678"
      ACCEPT_EULA: "Y"
    # volumes:
    #     - ./data/mssql:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - findatutor

  api:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: find-a-tutor.api
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - sql__connectionString=Server=db,1433;User Id=SA;Password=Abc12345678;Database=FindATutor
    depends_on:
      - db
    ports:
      - 5000:80
    networks:
      - findatutor

  front:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: find-a-tutor.front
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiUrl=http://api:80
    ports:
      - 8000:80
    networks:
      - findatutor
    depends_on:
      - api
  
networks:
  findatutor:
    name: findatutor-network
    external: false